import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/sections/navbar/default";
import Footer from "@/components/sections/footer/page";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link href="https://api.fontshare.com/v2/css?f[]=satoshi@600&display=swap" rel="stylesheet" /> 
      <link href="https://api.fontshare.com/v2/css?f[]=cabinet-grotesk@500&display=swap" rel="stylesheet" /> 
      </head>
      <body
      >
        <Navbar />
        {children}
        <Footer />

      </body>
    </html>
  );
}
